### ISSUE TITLE
Get all siblings

### ISSUE THREAD

**Issue by razvanphp** [paulzi/yii2-adjacency-list#10]
Hello, thank you for this great extension.

Is there a better (more elegant/faster) way to do this?

`$node->getParent()->one()->getDescendants()->all()`

Cheers,
R

**Comment by paulzi** [comment]
Hello, @razvanphp !
If you need to get all the nodes for the parent (including the neighbors node `$node`), then yes, this is the only one way to do this.
The only thing that, to make it look more elegant, and the data is not retrieved from the database again, you can use the syntax:
```php
$allNodes = $node->parent->descendants;
```

**Comment by lvbaocheng** [comment]
Undefined property:model::$descendants.Did I miss something?Thanks for your help

**Comment by paulzi** [comment]
@lvbaocheng, please provide the model code.

**Comment by lvbaocheng** [comment]
Thank you! The fields in the project table are id,name and parent, no other.Parent default is 'null'.

\models\Project.php

use AutoTreeTrait;

public function behaviors()
    {
        return [
            [
                'class' => AdjacencyListBehavior::className(),
                'sortable' => false,
                'parentAttribute' => 'parent',
            ],
        ];
    }

public function transactions()
    {
        return [
            self::SCENARIO_DEFAULT => self::OP_ALL,
        ];
    }

public static function find()
    {
        return new GroupsQuery(get_called_class());
    }


--------------------------------------------------------
\models\ProjectQuery.php

use AdjacencyListQueryTrait;

**Comment by lvbaocheng** [comment]
$model = $this->findModel(104);
$allNodes = $model->getParent()->one()->getDescendants()->asArray()->all();

This is no problem.But   $this->findModel(1)  no way.
Error:Call to a member function getDescendants() on null

**Comment by paulzi** [comment]
Does the element with id = 104 have a parent?

**Comment by lvbaocheng** [comment]
@paulzi Yes,the parent node is 1

**Comment by paulzi** [comment]
You seem to have an attribute name conflict with the `getParent()` method, and means and with relation `parent`

**Comment by lvbaocheng** [comment]
No!No!No! Or i miss something?
![bb22 od 1a30_ auii cn8a](https://user-images.githubusercontent.com/6335294/34336713-4c02d4c0-e994-11e7-9e13-0f4d5c3b7573.png)

-----------------------------------------------
### ##id = 1:
![8cs60eg82k 8kn vy1 _y7o](https://user-images.githubusercontent.com/6335294/34336823-5a667570-e995-11e7-8941-7d76d49ebce0.png)
-----------------------------------------------
### ##id = 9, it is ok:
![Uploading 234.png…]()


### ##Add 'descendants':
![4 1dl 3z0jtq1ufl 6n _pd](https://user-images.githubusercontent.com/6335294/34337005-c4740cf6-e996-11e7-86ec-b8a12bf22528.png)

![74y8 e 36 _7cu d kmp0n](https://user-images.githubusercontent.com/6335294/34337012-d35595b4-e996-11e7-88fc-bf65d25480a3.png)

**Comment by paulzi** [comment]
You provide this code:
```
'parentAttribute' => 'parent',
```
You are missed `_id`?

**Comment by paulzi** [comment]
For `id = 1` parent is null, it is ok. For this node, `parent_id` is specified `null` in [the table](https://user-images.githubusercontent.com/6335294/34336713-4c02d4c0-e994-11e7-9e13-0f4d5c3b7573.png).
If you need simple get all descendants for node id=1, just write:
```php
$model = $this->findModel(1);
$allNodes = $model->getDescendants()->asArray()->all();
```

**Comment by lvbaocheng** [comment]
Problem one: my model has no problem, this is another simple example I showed you. It's not so careless, haha!
Problem two: If you do this, there are some problems in the screenshot, please look at the content of the screenshot in detail, and you can try a simple example.
