### ISSUE TITLE
Получение предков через with

### ISSUE THREAD

**Issue by wispoz** [paulzi/yii2-adjacency-list#12]
Можно ли как-то сделать получение предков / потомков через relation? 
Например  : 
`$node = Task::find()->where(['id'=>1])->with('parents')->one();`

**Comment by paulzi** [comment]
Нет, так как данная связь сделана не через hasOne/hasMany Yii2 не умеет агрегировать такие запросы.

**Comment by wispoz** [comment]
А как тогда можно получить потомков  / предков при использовании asArray? 
`$node = Task::find()->where(['id'=>1])->asArray()->one();`

**Comment by paulzi** [comment]
Ну так просто не получится. Надо писать свою реализацию для этого.
