### ISSUE TITLE
Где взять примеры функций для работы с деревом?

### ISSUE THREAD

**Issue by kwazaro** [paulzi/yii2-adjacency-list#5]
Где взять примеры функций для вывода целого дерева (например, для визуального его отображения на сайте) и вывода "хлебных крошек" (в формате массива для виджета Yii2 Breadcrumbs)?

**Comment by paulzi** [comment]
А какие тут могут быть примеры, пишется же элементарно:

``` php
function outNode($node) {
    $result = null;
    if ($node->children) {
        foreach ($node->children as $child) {
            $result .= outNode($child);
        }
        $result = "<ul>{$result}</ul>";
    }
    return "<li>{$node->title}{$result}</li>";
}

$root->populateTree(); // получаем всё дерево из базы сразу
echo outNode($root);
```

А хлебные крошки к деревьям вообще мало отношения имеют, в него передаётся обычный массив элементов.

**Comment by kwazaro** [comment]
За пример вывода списка - спасибо.

Про хлебные крошки я имел ввиду готовый массив для передачи в стандартный виджет фреймворка (ведь это дополнение к фреймворку, Yii2 верно?). Этот массив отображает полный путь от корня дерева к текущей ноде. Было бы неплохо иметь в документации к данному дополнению примеры функций для таких задач. Либо внедрить такую функцию в само дополнение.

При использования дерева Adjacency List при добавлении новой ноды вполне логично заполнение поля формы с названием "parent_id". Наиболее удобный и наглядный способ - это выпадающий список (select) для этого поля. Для формирования такого списка во фреймворке нужен одномерный массив всего дерева, правильно отсортированный. В массиве ключи - это id нод, а значения - допустим имя (аттрибут "name" для модели). В итоге должно получиться такое:

``` php
$items = [
    1 => 'Каталог товара (корень)',
    2 => '--Категория 1',
    3 => '----Категория 1.1',
    4 => '----Категория 1.2',
    5 => '--Категория 2',
    6 => '----Категория 2.1',
    7 => '----Категория 2.2',
    8 => '----Категория 2.3',
    // ...
];
```

Существует две проблемы: при обычной выборке сортировка происходит не так. Сначала выводятся родители, потом дети. Вторая проблема: так как массив одномерный, указание "глубины" уровня происходит (в моём случае) добавлением к названию элемента двойного тире "--" для наглядности. Если уровень вложенности 2 - то четыре тире итд. Визуально такой выпадающий список похож на дерево и удобен для выбора родителя в форме.
Каким образом можно осуществить такую задачу? Я думаю не только мне одному это интересно, так как задача важная для создания интерфейса управления деревом.

**Comment by paulzi** [comment]
Не следует смешивать логику с представлением. Данный набор Behaviors обеспечивает систему хранения, и к пользовательскому интерфейсу вообще не должен иметь никакого отношения, а вывод у каждого может по своему осуществляться, у кого-то это выпадающий список, а у кого-то виджет tree-плагина с AJAX подгрузкой. А так как надо всегда стараться держаться принципа "на одну задачу - одна утилита", не вижу смысла внедрять подобного рода функционал в поведение. Если вам требуется подобное в вашем проекте, просто расширьте класс поведения.

А по поводу описания примера для Breadcrumbs, на мой взгляд это слишком очевидно и просто, чтобы это описывать, да и не связаны компоненты, и слишком зависимы от роутов в вашем приложении. Например, у меня в проекте breadcrumbs может выглядеть так:

``` php
$links = [];
$links[] = [
    'label' => 'Products',
    'url' => ['product/index'],
];
foreach ($node->parentsOrdered as $parent) {
    $links[] = [
        'label' => $parent->title,
        'url' => ['product/index', 'path' => $parent->path],
    ];
}
Breadcrumbs::widget(['links' => $links]);
```
