### ISSUE TITLE
Table alias error

### ISSUE THREAD

**Issue by netsnatch** [paulzi/yii2-adjacency-list#9]
I get this error 
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'categories.parent_id' in 'where clause'
The SQL being executed was: SELECT MAX(sort) FROM `categories` `cat` WHERE categories.`parent_id`=4

```
Category model:
```
    public static function find()
    {
        return (new CategoryQuery(get_called_class()))->alias('cat');
    }
```

The problem is in using `$this->owner->tableName()`

**Comment by paulzi** [comment]
Yii2 does not have methods for getting the current alias of query. In `yii\db\ActiveQuery` exist method `getTableNameAndAlias()`, but it's private. In main yii2 repo, there are several issue and pull-requests:
https://github.com/yiisoft/yii2/issues/7263
https://github.com/yiisoft/yii2/pull/11646
Without method `getTableAlias()`, it is difficult to implement the getting of the current table alias and I need to duplicate this private method.
Therefore, aliases are not currently supported.

**Comment by netsnatch** [comment]
I propose to delete the name of the table and leave only the name of the field.

**Comment by paulzi** [comment]
It is possible, but if you use joins, then the absence of aliases will also generate errors.
I will try to deal with this issue without waiting for a solution in the framework.

**Comment by netsnatch** [comment]
Thanks
